### PR TITLE
Add travis ci

### PR DESCRIPTION
**Pull request by gabrielf**

### CODE REVIEW

**Comment by gabrielf** [comment]
The travis build will fail until #17 (or similar) is accepted.

**Comment by ConradIrwin** [comment]
Should we also test on 1.9?

**Comment by gabrielf** [comment]
I choose 1.8 since that's what AppEngine uses and 1.10 since that's the latest but I guess 1.9 wouldn't hurt! :-D

**Comment by ConradIrwin** [comment]
Ah, interesting; that seems fine. I wonder why appengine hasn't upgraded...

Sent via Superhuman ( https://sprh.mn/?vip=conradirwin@gmail.com )

**Pull request merged**
